#!/bin/bash

# Copy .env file
echo "##########################"
echo "### Creating .env file ###"
echo "##########################"
if [ ! -f .env ]; then
    cp .env.example .env
fi

# Build docker images
echo "#######################"
echo "### Building images ###"
echo "#######################"
# docker-compose build

echo "###########################"
echo "### Starting containers ###"
echo "###########################"
docker-compose up -d --build

# Composer dependencies
echo "########################################"
echo "### Installing composer dependencies ###"
echo "########################################"
docker run --rm --interactive --tty \
    --volume $PWD/www:/app \
    composer install

# NPM dependencies
echo "###################################"
echo "### Installing npm dependencies ###"
echo "###################################"
# docker run -v $PWD/www:/app -w /app node:8.9.4 npm install
./run npm install

# Application setup
echo "#########################"
echo "### Application setup ###"
echo "#########################"
./run php artisan key:generate
./run php artisan migrate
./run php artisan db:seed

echo "### DONE! ###"
echo ""
echo "http://localhost:8089/"
echo ""